name: 'add-gcal-event'
on:
  workflow_dispatch:

jobs:
  run:
    name: 'example to list calendar events'
    permissions:
      id-token: write
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
    - id: 'setup-python'
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - id: 'checkout-repo'
      uses: actions/checkout@v3
    - id: 'install-requirements'
      run: 'pip install -r requirements.txt'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKFLOW_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SA_NAME }} # service account email
        token_format: 'access_token'
    - id: 'add-calendar-event'
      env:
        calendar_id: ${{ secrets.CALENDAR_ID }}
      run: python add_calendar_event.py